<?php
/**
 * @file
 * Code for the HPPS: Global feature.
 */

include_once 'hpps_global.features.inc';

/**
 * Implements hook_form_alter().
 */
function hpps_global_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'registration_form') {
    $form['who_is_registering']['#type'] = 'value';
    $form['who_is_registering']['#value'] = 'registration_registrant_type_anon';
  }
}

/**
 * Implements hook_menu_alter().
 */
function hpps_global_menu_alter(&$items) {
  // make the entity_registration path a non-tab item
  $items['node/%entity_object/register']['type'] = MENU_CALLBACK;
}